---
title: "**Assignment 01 - Group 3**"
author: "Daniel + Megan + Mike"
date: "26 October 2021"
output: 
  html_document:
    theme: readable
    toc: true
    toc_depth: 3
    toc_float:  true
---
<style>
body {
text-align: justify}
</style>


```{r load library, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(tidycensus)
library(readxl)
library(knitr)
```

# research question
How well does a census tract’s percentage of single-family homes and location relative to metropolitan center predict the average home value and tenure period in homes for the Commonwealth of Massachusetts?

# prior research
While the correlation between diversity of housing types and racial and economic diversity in	neighborhoods have previously been established, this study investigated a potential 	relationship between housing typology and foreclosures. In fact, they found a positive (but varied) correlation between type and stability—neighborhoods with a range of housing stock had lower foreclosure and sales rates (Chakraborty et al 2018). Additionally, hedonic modelling of home values have been shown to respond to distance to city center. Longer distance from the metropolitan center correlates with lower property values in the magnitude of 1.82%. However, this relationship is highly income dependent, where devaluation associated with distance is higher for low-income individuals than for high-income individuals (Kestens et al. 2006).

- Chakraborty, Arnab and McMillan, Andrew, “Is Housing Diversity Good for Community Stability?: Evidence from the Housing Crisis,” *Journal of Planning Education and Research*, (2018), https://journals.sagepub.com/doi/10.1177/0739456X18810787
- Kestens, Yan,  Theriault, Marius, and Des Rosiers  Francois "Heterogeneity in hedonic modelling of house
prices: looking at buyers’ household profiles," *Journal of Geographical Systems*, (2006), https://link.springer.com/article/10.1007/s10109-005-0011-8

# data
The sample population for this study is the full set of all census tracts in the Commonwealth of Massachusetts. 

The analysis will include the following variables:

- **Percentage of Single-family Homes** (DataCommon - mapc.gov)
- **Average Housing Tenure of Units** (DataCommon - mapc.gov)
- **Value of Building Structure with Land** (DataCommon - mapc.gov)
- **Percent of Whiteness of Residents in Census Tract** (United States Census Bureau 2020)
- **Urban Rural Classification** (National Center for Health Statistics 2013)